export const GET_ALL_ARTICLE_REQUESTED = 'GET_ALL_ARTICLE_REQUESTED';
export const GET_ARTICLE_REQUESTED     = 'GET_ARTICLE_REQUESTED';
export const GET_ARTICLE_SUCCESS       = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILED        = 'GET_ARTICLE_FAILED';